/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EventCreate
 */
export interface EventCreate {

    /**
     * @type {string}
     * @memberof EventCreate
     */
    title: string;

    /**
     * @type {string}
     * @memberof EventCreate
     */
    description: string;

    /**
     * @type {number}
     * @memberof EventCreate
     */
    organization: number;

    /**
     * @type {Date}
     * @memberof EventCreate
     */
    startDate: Date;

    /**
     * @type {Date}
     * @memberof EventCreate
     */
    endDate: Date;

    /**
     * @type {string}
     * @memberof EventCreate
     */
    location: string;
}
