/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Organization } from './organization';
 /**
 * 
 *
 * @export
 * @interface Event
 */
export interface Event {

    /**
     * @type {number}
     * @memberof Event
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Event
     */
    title: string;

    /**
     * @type {string}
     * @memberof Event
     */
    description: string;

    /**
     * @type {Organization}
     * @memberof Event
     */
    organization?: Organization;

    /**
     * @type {Date}
     * @memberof Event
     */
    startDate: Date;

    /**
     * @type {Date}
     * @memberof Event
     */
    endDate: Date;

    /**
     * @type {string}
     * @memberof Event
     */
    location: string;

    /**
     * @type {string}
     * @memberof Event
     */
    maxParticipants?: string;

    /**
     * @type {boolean}
     * @memberof Event
     */
    isActive?: boolean;

    /**
     * @type {Date}
     * @memberof Event
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof Event
     */
    updatedAt?: Date;
}
