/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TicketType } from './ticket-type';
 /**
 * 
 *
 * @export
 * @interface Ticket
 */
export interface Ticket {

    /**
     * @type {number}
     * @memberof Ticket
     */
    id?: number;

    /**
     * @type {TicketType}
     * @memberof Ticket
     */
    ticketType?: TicketType;

    /**
     * @type {string}
     * @memberof Ticket
     */
    status?: TicketStatusEnum;

    /**
     * @type {string}
     * @memberof Ticket
     */
    ticketNumber: string;

    /**
     * @type {string}
     * @memberof Ticket
     */
    notes?: string;

    /**
     * @type {string}
     * @memberof Ticket
     */
    event?: string;

    /**
     * @type {Date}
     * @memberof Ticket
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof Ticket
     */
    updatedAt?: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum TicketStatusEnum {
    Pending = 'pending',
    Confirmed = 'confirmed',
    Cancelled = 'cancelled',
    Expired = 'expired'
}

